import {
  getDocs,
  getDoc,
  setDoc,
  updateDoc,
  deleteDoc,
  onSnapshot,
  getCountFromServer,
  Timestamp,
} from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { COL, athletesCol, athleteDoc } from '@/lib/firebase/collections';
import type { Athlete } from '@/lib/types';

/** One-time fetch of all athletes. */
export async function getAthletes(): Promise<Athlete[]> {
  const snap = await getDocs(athletesCol);
  return snap.docs.map((d) => d.data());
}

/** Real-time subscription. Returns unsubscribe function. */
export function subscribeAthletes(
  onData: (athletes: Athlete[]) => void,
  onError?: (err: Error) => void,
): () => void {
  return onSnapshot(
    athletesCol,
    (snap) => onData(snap.docs.map((d) => d.data())),
    (err) => onError?.(err),
  );
}

/** Fetch a single athlete by id. */
export async function getAthlete(id: string): Promise<Athlete | null> {
  const snap = await getDoc(athleteDoc(id));
  return snap.exists() ? snap.data() : null;
}

/** Total athlete count (cheap server-side count). */
export async function getAthleteCount(): Promise<number> {
  const snap = await getCountFromServer(athletesCol);
  return snap.data().count;
}

/** Create a new athlete. id is generated by the caller. */
export async function addAthlete(
  data: Omit<Athlete, 'id'> & { athleteId?: string },
): Promise<string> {
  const id = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  await setDoc(athleteDoc(id), { id, athleteId: id, ...data, createdAt: Timestamp.now() } as Athlete);
  return id;
}

/** Update an existing athlete. */
export async function updateAthlete(
  id: string,
  data: Partial<Omit<Athlete, 'id'>>,
): Promise<void> {
  await updateDoc(athleteDoc(id), { ...data, updatedAt: Timestamp.now() });
}

/** Delete an athlete permanently. */
export async function deleteAthlete(id: string): Promise<void> {
  await deleteDoc(athleteDoc(id));
}
