import {
  getDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  onSnapshot,
  getCountFromServer,
  Timestamp,
} from 'firebase/firestore';
import { competitionsCol, competitionDoc } from '@/lib/firebase/collections';
import type { Competition } from '@/lib/types';

/** One-time fetch of all competitions. */
export async function getCompetitions(): Promise<Competition[]> {
  const snap = await getDocs(competitionsCol);
  return snap.docs.map((d) => d.data());
}

/** Real-time subscription. Returns unsubscribe function. */
export function subscribeCompetitions(
  onData: (competitions: Competition[]) => void,
  onError?: (err: Error) => void,
): () => void {
  return onSnapshot(
    competitionsCol,
    (snap) => onData(snap.docs.map((d) => d.data())),
    (err) => onError?.(err),
  );
}

/** Total competition count (cheap server-side count). */
export async function getCompetitionCount(): Promise<number> {
  const snap = await getCountFromServer(competitionsCol);
  return snap.data().count;
}

/** Create a new competition. id is generated by the caller. */
export async function addCompetition(
  data: Omit<Competition, 'id'> & { events?: Record<string, boolean> },
): Promise<string> {
  const id = Date.now().toString(36);
  await setDoc(competitionDoc(id), { id, ...data, createdAt: Timestamp.now() } as Competition);
  return id;
}

/** Update an existing competition. */
export async function updateCompetition(
  id: string,
  data: Partial<Omit<Competition, 'id'>>,
): Promise<void> {
  await updateDoc(competitionDoc(id), { ...data, updatedAt: Timestamp.now() });
}

/** Delete a competition permanently. */
export async function deleteCompetition(id: string): Promise<void> {
  await deleteDoc(competitionDoc(id));
}

/** Officially finish a competition: set status='finished' and finishedAt=now. */
export async function finishCompetition(id: string): Promise<void> {
  const now = Timestamp.now();
  await updateDoc(competitionDoc(id), {
    status: 'finished',
    finishedAt: now,
    updatedAt: now,
  });
}
