import {
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  deleteDoc,
  onSnapshot,
  getCountFromServer,
  Timestamp,
} from 'firebase/firestore';
import { competitionsCol, competitionDoc } from '@/lib/firebase/collections';
import type { Competition } from '@/lib/types';

/** Fixed id of the singleton Daily Practice pseudo-competition (see
 *  ensureDailyPracticeCompetition below). One evergreen doc, not one per
 *  day — per-day uniqueness is enforced on the Result docId instead. */
export const DAILY_PRACTICE_COMPETITION_ID = 'daily-practice';

/** One-time fetch of all competitions. */
export async function getCompetitions(): Promise<Competition[]> {
  const snap = await getDocs(competitionsCol);
  return snap.docs.map((d) => d.data());
}

/** Real-time subscription. Returns unsubscribe function. */
export function subscribeCompetitions(
  onData: (competitions: Competition[]) => void,
  onError?: (err: Error) => void,
): () => void {
  return onSnapshot(
    competitionsCol,
    (snap) => onData(snap.docs.map((d) => d.data())),
    (err) => onError?.(err),
  );
}

/** Total competition count (cheap server-side count). */
export async function getCompetitionCount(): Promise<number> {
  const snap = await getCountFromServer(competitionsCol);
  return snap.data().count;
}

/** Create a new competition. id is generated by the caller. */
export async function addCompetition(
  data: Omit<Competition, 'id'> & { events?: Record<string, boolean> },
): Promise<string> {
  const id = Date.now().toString(36);
  await setDoc(competitionDoc(id), { id, ...data, createdAt: Timestamp.now() } as Competition);
  return id;
}

/** Update an existing competition. */
export async function updateCompetition(
  id: string,
  data: Partial<Omit<Competition, 'id'>>,
): Promise<void> {
  await updateDoc(competitionDoc(id), { ...data, updatedAt: Timestamp.now() });
}

/** Delete a competition permanently. */
export async function deleteCompetition(id: string): Promise<void> {
  await deleteDoc(competitionDoc(id));
}

/** Officially finish a competition: set status='finished' and finishedAt=now. */
export async function finishCompetition(id: string): Promise<void> {
  const now = Timestamp.now();
  await updateDoc(competitionDoc(id), {
    status: 'finished',
    finishedAt: now,
    updatedAt: now,
  });
}

/**
 * Create the Daily Practice pseudo-competition doc if it doesn't exist yet.
 * Idempotent — safe to call on every ResultsEntryTab mount. Status stays
 * 'live' forever so it never enters `useResults`' finished-only feed (kept
 * out of Rankings/Records/public Athlete history), and `isDailyPractice`
 * lets every "list real competitions" call site filter it out.
 */
export async function ensureDailyPracticeCompetition(): Promise<void> {
  const ref = competitionDoc(DAILY_PRACTICE_COMPETITION_ID);
  const snap = await getDoc(ref);
  if (snap.exists()) return;
  await setDoc(ref, {
    id: DAILY_PRACTICE_COMPETITION_ID,
    name: 'Daily Practice',
    status: 'live',
    isDailyPractice: true,
    createdAt: Timestamp.now(),
  } as Competition);
}
