// Countries for the ХОРОМ profile picker.
// Extracted verbatim from the approved mockup (Khorom v2 - Dark Platform).
// `code` is the ISO 3166-1 alpha-2 code, lowercase — it is the value STORED in Firestore.
// `name` is the Mongolian display name. Never store the name.

export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "af", name: "Афганистан" },
  { code: "al", name: "Албани" },
  { code: "dz", name: "Алжир" },
  { code: "ad", name: "Андорра" },
  { code: "ao", name: "Ангол" },
  { code: "ag", name: "Антигуа ба Барбуда" },
  { code: "ar", name: "Аргентин" },
  { code: "am", name: "Армен" },
  { code: "au", name: "Австрали" },
  { code: "at", name: "Австри" },
  { code: "az", name: "Азербайжан" },
  { code: "bs", name: "Багам" },
  { code: "bh", name: "Бахрейн" },
  { code: "bd", name: "Бангладеш" },
  { code: "bb", name: "Барбадос" },
  { code: "by", name: "Беларусь" },
  { code: "be", name: "Бельги" },
  { code: "bz", name: "Белиз" },
  { code: "bj", name: "Бенин" },
  { code: "bt", name: "Бутан" },
  { code: "bo", name: "Боливи" },
  { code: "ba", name: "Босни Герцеговин" },
  { code: "bw", name: "Ботсван" },
  { code: "br", name: "Бразил" },
  { code: "bn", name: "Бруней" },
  { code: "bg", name: "Болгар" },
  { code: "bf", name: "Буркина Фасо" },
  { code: "bi", name: "Бурунди" },
  { code: "kh", name: "Камбож" },
  { code: "cm", name: "Камерун" },
  { code: "ca", name: "Канад" },
  { code: "cv", name: "Кабо Верде" },
  { code: "cf", name: "Төв Африк" },
  { code: "td", name: "Чад" },
  { code: "cl", name: "Чили" },
  { code: "cn", name: "Хятад" },
  { code: "co", name: "Колумб" },
  { code: "km", name: "Комор" },
  { code: "cg", name: "Конго" },
  { code: "cd", name: "БНАКонго" },
  { code: "cr", name: "Коста Рика" },
  { code: "ci", name: "Кот-д'Ивуар" },
  { code: "hr", name: "Хорват" },
  { code: "cu", name: "Куба" },
  { code: "cy", name: "Кипр" },
  { code: "cz", name: "Чех" },
  { code: "dk", name: "Дани" },
  { code: "dj", name: "Жибути" },
  { code: "dm", name: "Доминика" },
  { code: "do", name: "Доминикан" },
  { code: "ec", name: "Эквадор" },
  { code: "eg", name: "Египет" },
  { code: "sv", name: "Эль Сальвадор" },
  { code: "gq", name: "Экваторын Гвиней" },
  { code: "er", name: "Эритрей" },
  { code: "ee", name: "Эстони" },
  { code: "sz", name: "Эсватини" },
  { code: "et", name: "Этиоп" },
  { code: "fj", name: "Фижи" },
  { code: "fi", name: "Финлянд" },
  { code: "fr", name: "Франц" },
  { code: "ga", name: "Габон" },
  { code: "gm", name: "Гамби" },
  { code: "ge", name: "Гүрж" },
  { code: "de", name: "Герман" },
  { code: "gh", name: "Гана" },
  { code: "gr", name: "Грек" },
  { code: "gd", name: "Гренада" },
  { code: "gt", name: "Гватемал" },
  { code: "gn", name: "Гвиней" },
  { code: "gw", name: "Гвиней-Бисау" },
  { code: "gy", name: "Гайана" },
  { code: "ht", name: "Гаити" },
  { code: "hn", name: "Гондурас" },
  { code: "hu", name: "Унгар" },
  { code: "is", name: "Исланд" },
  { code: "in", name: "Энэтхэг" },
  { code: "id", name: "Индонез" },
  { code: "ir", name: "Иран" },
  { code: "iq", name: "Ирак" },
  { code: "ie", name: "Ирланд" },
  { code: "il", name: "Израиль" },
  { code: "it", name: "Итали" },
  { code: "jm", name: "Ямайка" },
  { code: "jp", name: "Япон" },
  { code: "jo", name: "Йордан" },
  { code: "kz", name: "Казахстан" },
  { code: "ke", name: "Кени" },
  { code: "ki", name: "Кирибати" },
  { code: "kw", name: "Кувейт" },
  { code: "kg", name: "Киргиз" },
  { code: "la", name: "Лаос" },
  { code: "lv", name: "Латви" },
  { code: "lb", name: "Ливан" },
  { code: "ls", name: "Лесото" },
  { code: "lr", name: "Либери" },
  { code: "ly", name: "Ливи" },
  { code: "li", name: "Лихтенштейн" },
  { code: "lt", name: "Литва" },
  { code: "lu", name: "Люксембург" },
  { code: "mg", name: "Мадагаскар" },
  { code: "mw", name: "Малави" },
  { code: "my", name: "Малайз" },
  { code: "mv", name: "Мальдив" },
  { code: "ml", name: "Мали" },
  { code: "mt", name: "Мальт" },
  { code: "mh", name: "Маршаллын арлууд" },
  { code: "mr", name: "Мавритани" },
  { code: "mu", name: "Маврики" },
  { code: "mx", name: "Мексик" },
  { code: "fm", name: "Микронез" },
  { code: "md", name: "Молдав" },
  { code: "mc", name: "Монако" },
  { code: "mn", name: "Монгол" },
  { code: "me", name: "Монтенегро" },
  { code: "ma", name: "Марокко" },
  { code: "mz", name: "Мозамбик" },
  { code: "mm", name: "Мьянмар" },
  { code: "na", name: "Намиби" },
  { code: "nr", name: "Науру" },
  { code: "np", name: "Балба" },
  { code: "nl", name: "Нидерланд" },
  { code: "nz", name: "Шинэ Зеланд" },
  { code: "ni", name: "Никарагуа" },
  { code: "ne", name: "Нигер" },
  { code: "ng", name: "Нигери" },
  { code: "kp", name: "Хойд Солонгос" },
  { code: "mk", name: "Хойд Македон" },
  { code: "no", name: "Норвег" },
  { code: "om", name: "Оман" },
  { code: "pk", name: "Пакистан" },
  { code: "pw", name: "Палау" },
  { code: "ps", name: "Палестин" },
  { code: "pa", name: "Панам" },
  { code: "pg", name: "Папуа Шинэ Гвиней" },
  { code: "py", name: "Парагвай" },
  { code: "pe", name: "Перу" },
  { code: "ph", name: "Филиппин" },
  { code: "pl", name: "Польш" },
  { code: "pt", name: "Португал" },
  { code: "qa", name: "Катар" },
  { code: "ro", name: "Румын" },
  { code: "ru", name: "Орос" },
  { code: "rw", name: "Руанда" },
  { code: "kn", name: "Сент-Китс Невис" },
  { code: "lc", name: "Сент-Люси" },
  { code: "vc", name: "Сент-Винсент" },
  { code: "ws", name: "Самоа" },
  { code: "sm", name: "Сан-Марино" },
  { code: "st", name: "Сан-Томе Принсипи" },
  { code: "sa", name: "Саудын Араб" },
  { code: "sn", name: "Сенегал" },
  { code: "rs", name: "Серби" },
  { code: "sc", name: "Сейшел" },
  { code: "sl", name: "Сьерра-Леоне" },
  { code: "sg", name: "Сингапур" },
  { code: "sk", name: "Словак" },
  { code: "si", name: "Словени" },
  { code: "sb", name: "Соломоны арлууд" },
  { code: "so", name: "Сомали" },
  { code: "za", name: "Өмнөд Африк" },
  { code: "kr", name: "Өмнөд Солонгос" },
  { code: "ss", name: "Өмнөд Судан" },
  { code: "es", name: "Испани" },
  { code: "lk", name: "Шри-Ланка" },
  { code: "sd", name: "Судан" },
  { code: "sr", name: "Суринам" },
  { code: "se", name: "Швед" },
  { code: "ch", name: "Швейцарь" },
  { code: "sy", name: "Сири" },
  { code: "tw", name: "Тайвань" },
  { code: "tj", name: "Тажикистан" },
  { code: "tz", name: "Танзани" },
  { code: "th", name: "Тайланд" },
  { code: "tl", name: "Зүүн Тимор" },
  { code: "tg", name: "Того" },
  { code: "to", name: "Тонга" },
  { code: "tt", name: "Тринидад Тобаго" },
  { code: "tn", name: "Тунис" },
  { code: "tr", name: "Турк" },
  { code: "tm", name: "Туркменистан" },
  { code: "tv", name: "Тувалу" },
  { code: "ug", name: "Уганда" },
  { code: "ua", name: "Украин" },
  { code: "ae", name: "АНЭУ" },
  { code: "gb", name: "Их Британи" },
  { code: "us", name: "АНУ" },
  { code: "uy", name: "Уругвай" },
  { code: "uz", name: "Узбекистан" },
  { code: "vu", name: "Вануату" },
  { code: "va", name: "Ватикан" },
  { code: "ve", name: "Венесуэл" },
  { code: "vn", name: "Вьетнам" },
  { code: "ye", name: "Йемен" },
  { code: "zm", name: "Замби" },
  { code: "zw", name: "Зимбабве" },
];

export const DEFAULT_COUNTRY_CODE = 'mn';

export function flagUrl(code: string): string {
  return `https://flagcdn.com/w40/${code}.png`;
}

export function countryName(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code;
}
